"""puts_smalls_shapes_sorter — Vision-Tactile-Language-Action (VTLA) task.

2–4 small shapes are randomly selected and spawned on the table each episode.
A natural-language instruction specifies which shape the robot must grasp and
drop into a sorter block placed in front of the robot.

Shape assets generated by scripts/generate_sorter.py
(--clearance 1.0 --scale 0.01 --tess 0.05 --out ./usd_shapes):
  cube               cube.usd         (~0.22 × 0.22 × 0.30 m, Z-centred)
  cylinder           cylinder.usd     (~Ø0.22 × 0.30 m, Z-centred)
  triangular prism   triangular_prism.usd
  star               star.usd
  moon               moon.usd
  sorter block       shape_sorter.usd (~2.0 × 0.6 × 0.40 m, Z-centred)

All generated USD assets are Z-centred (CadQuery origin = geometric centre).
With --scale 0.01 each shape piece is 0.30 m tall, so the spawn pose Z must
equal half the height (0.15 m) to rest the bottom on the table surface (z≈0).

Episode flow
------------
1. N_OBJECTS_PER_EPISODE shapes are drawn at random (without replacement).
2. A target shape is chosen; a language instruction is sampled from its pool.
3. pre_move: open gripper.
4. _play_once: grasp the target shape and drop it into the sorter hole.
5. check_success: target shape is inside the sorter zone.
"""

from ._base_task import *
import numpy as np
from pxr import UsdGeom, Gf
import omni.usd

def set_invisible(actor):
    prim = actor.prim
    img = UsdGeom.Imageable(prim)
    img.MakeInvisible()

# ── Configurable shape asset list ────────────────────────────────────────────
# Assets generated by scripts/generate_sorter.py --scale 0.01.
# All pieces are 0.30 m tall, Z-centred → grasp_z is relative to object centre.
# Hole order in the sorter block: cube | cylinder | triangle | star | moon
DELTA_HOLES = 0.078
SHAPE_CONFIGS: dict[str, dict] = {
    'cube': {
        'asset_path': 'cube.usd',
        'density': 15.0,
        'grasp_z': 0.012,
        "grasp_pos_floor": 0.040/0.078,
        'hole_x_offset': -2*DELTA_HOLES,
        'canonical_axis':    [1, 0, 0],
        'target_sorter_axis': [1, 0, 0],
        'symmetry_order':    4,
        'instructions': [
            "Grasp the cube and put it in the sorter.",
            "Pick up the cube block and drop it into the sorter.",
            "Take the cubic shape and place it in the sorter block.",
            "Grab the square block and put it inside the sorter.",
            "Pick the cube and insert it into the sorting slot.",
        ],
    },
    'cylinder': {
        'asset_path': 'cylinder.usd',
        'density': 15.0,
        'grasp_z': 0.012,
        "grasp_pos_floor": 0.037/0.078,
        'hole_x_offset': -DELTA_HOLES,
        'canonical_axis':    None,
        'instructions': [
            "Grasp the cylinder and put it in the sorter.",
            "Pick up the cylindrical shape and drop it into the sorter.",
            "Take the round column and place it in the sorter block.",
            "Grab the cylinder and put it inside the sorter.",
            "Pick the tube-shaped piece and insert it into the sorting slot.",
        ],
    },
    'triangular_prism': {
        'asset_path': 'triangular_prism.usd',
        'density': 15.0,
        'grasp_z': 0.012,
        'hole_x_offset': 0.0,
        "grasp_pos_floor": 0.035/0.078,
        'canonical_axis':    [0, 1, 0],
        'target_sorter_axis': [0, 1, 0],
        'symmetry_order':    3,
        'instructions': [
            "Grasp the triangular prism and put it in the sorter.",
            "Pick up the triangular shape and drop it into the sorter.",
            "Take the triangle block and place it in the sorter block.",
            "Grab the triangular piece and put it inside the sorter.",
            "Pick the triangle and insert it into the sorting slot.",
        ],
    },
    'star': {
        'asset_path': 'star.usd',
        'density': 15.0,
        'grasp_z': 0.012,
        "grasp_pos_floor": 0.030/0.078,
        'hole_x_offset': DELTA_HOLES,
        'canonical_axis':    [0, 1, 0],
        'target_sorter_axis': [0, 1, 0],
        'symmetry_order':    5,
        'instructions': [
            "Grasp the star shape and put it in the sorter.",
            "Pick up the star piece and drop it into the sorter.",
            "Take the five-pointed star and place it in the sorter block.",
            "Grab the star-shaped block and put it inside the sorter.",
            "Pick the star and insert it into the sorting slot.",
        ],
    },
    'moon': {
        'asset_path': 'moon.usd',
        'density': 15.0,
        'grasp_z': 0.012,
        "grasp_pos_floor": 0.018/0.078,
        'hole_x_offset': 2 * DELTA_HOLES,
        'canonical_axis':    [1, 0, 0],
        'target_sorter_axis': [1, 0, 0],
        'symmetry_order':    1,
        'instructions': [
            "Grasp the moon shape and put it in the sorter.",
            "Pick up the crescent piece and drop it into the sorter.",
            "Take the moon-shaped block and place it in the sorter block.",
            "Grab the crescent and put it inside the sorter.",
            "Pick the moon piece and insert it into the sorting slot.",
        ],
    },
}

ALL_SHAPE_NAMES: list[str] = list(SHAPE_CONFIGS.keys())

# Objects are ~0.22 m wide; 0.30 m spacing keeps them from touching.
GRID_SPACING_Y = 0.40

# ── Off-table parking position for unused / initial shapes ────────────────────
OFFSCREEN_X = 3
OFFSCREEN_Y_START = 3.0
OFFSCREEN_Z = 3

# Height used as intermediate waypoint during reset: above the sorter and gelsight.
SPAWN_SAFE_Z = 1
TABLE_SPAWN_Z        = 0.04

# ── Sorter drop zone ──────────────────────────────────────────────────────────
DRAWER_ASSET_PATH = 'shape_sorter.usd'
DRAWER_VISUAL_ASSET_PATH = 'shape_sorter.usd'

_DRAWER_BASE_POSE = Pose([0.5, 0, 0.051], [0.7071, 0, 0, 0.7071])

_SUCCESS_XY_TOL = 0.10
_SUCCESS_Z_MIN  = 0.05

# ── Task configuration ────────────────────────────────────────────────────────

@configclass
class TaskCfg(BaseTaskCfg):
    cameras = [
        CameraCfg(
            name="head",
            prim_path="/World/envs/env_.*/Camera",
            offset=CameraCfg.OffsetCfg(pos=(0.74, 0.0, 0.066), rot=(0.512, 0.512, 0.487, 0.487), convention="opengl"),
            data_types=["rgb", "depth"],
            spawn=sim_utils.PinholeCameraCfg(
                focal_length=2.5, focus_distance=1.0, horizontal_aperture=3.6, clipping_range=(0.1, 100.0)
            ),
            width=480,
            height=270,
            update_period=1/120
        ),
        CameraCfg(
            name="wrist",
            prim_path="/World/envs/env_.*/Robot/WristCamera/Camera",
            data_types=["rgb", "depth"],
            spawn=None, # use existing camera
            width=480,
            height=270,
            update_period=1/120,
        )
    ]
    step_lim: int              = 800
    use_adaptive_grasp: bool   = False
    use_force_grasp: bool      = True
    squeeze_steps: int         = 30
    force_fast = 50 
    force_slow = 20 
    n_objects: int             = 3 # Default value



# ── Task implementation ───────────────────────────────────────────────────────

class Task(BaseTask):
    def __init__(self, cfg: BaseTaskCfg, mode:Literal['collect', 'eval'] = 'collect', render_mode: str|None = None, **kwargs):
        cfg.sim.physics_material.dynamic_friction = 2.5
        cfg.sim.physics_material.static_friction = 2.5
        cfg.uipc_sim.contact.default_friction_ratio = 2.5
        super().__init__(cfg, mode, render_mode, **kwargs)

    def _drawer_collision_path(self) -> str:
        """USD prim path of the collision proxy mesh as spawned by actor_manager."""
        # actor_manager places actors under /World/envs/env_0/<name>
        return "/World/envs/env_0/drawer"

    def _spawn_visual_prim(self, name: str, asset_path: str, pose: Pose) -> str:
        """
        Add a USD file as a pure visual Xform (no CollisionAPI, no RigidBodyAPI).
        Returns the prim path string so _sync_visual_pose can update it each reset.
        """

        stage  = omni.usd.get_context().get_stage()
        path   = f"/World/envs/env_0/{name}"

        # Define an Xform and attach the USD file as a reference
        xform  = UsdGeom.Xform.Define(stage, path)
        xform.GetPrim().GetReferences().AddReference(asset_path)
        # No UsdPhysics.CollisionAPI / RigidBodyAPI applied → PhysX ignores it

        self._set_prim_pose(stage, path, pose)
        return path

    def _hide_prim(self, prim_path: str):
        """Make a prim invisible to the renderer (physics unaffected)."""
        stage = omni.usd.get_context().get_stage()
        prim  = stage.GetPrimAtPath(prim_path)
        if prim.IsValid():
            UsdGeom.Imageable(prim).MakeInvisible()

    def _sync_visual_pose(self):
        """Teleport the visual prim to match the collision proxy's current pose."""

        stage = omni.usd.get_context().get_stage()
        pose  = self._drawer.get_pose()          # authoritative pose from physics actor
        self._set_prim_pose(stage, "/World/envs/env_0/drawer", pose)

    @staticmethod
    def _set_prim_pose(stage, prim_path: str, pose: Pose):
        """Write a Pose to a prim using separate translate + orient ops."""

        xform = UsdGeom.Xformable.Get(stage, prim_path)
        if not xform:
            return

        p = pose.p
        w, x, y, z = pose.q

        # Clear existing ops and write translate + orient separately
        # (actor_manager already created these op types — match them)
        xform.ClearXformOpOrder()
        xform.AddTranslateOp().Set(Gf.Vec3d(float(p[0]), float(p[1]), float(p[2])))
        xform.AddOrientOp().Set(Gf.Quatd(float(w), float(x), float(y), float(z)))
    def create_actors(self):
        """Spawn all possible shape actors (hidden off-table) and the drawer."""
        # All shapes are created at episode init; unused ones are moved far away
        # in _reset_actors so the physics scene is reused without re-building.
        self._shapes: dict[str, Actor] = {}
        i = 0
        for name in ALL_SHAPE_NAMES:
            offscreen = Pose([OFFSCREEN_X, OFFSCREEN_Y_START - i * GRID_SPACING_Y, OFFSCREEN_Z], [1, 0, 0, 0])
            cfg = SHAPE_CONFIGS[name]
            actor = self._actor_manager.add_from_usd_file(
                name=name,
                asset_path=cfg['asset_path'],
                pose=offscreen,
                density=cfg['density'],
            )
            self._shapes[name] = actor
            i+=1

        # WARNING: drawer must be spawned at _DRAWER_OFFSCREEN_POSE (not _DRAWER_BASE_POSE).
        # ABD's write_vertex_positions_to_sim resets a body to its *initial* spawn pose
        # (identity q), so the drawer's init pose must be offscreen for the sequential
        # reset strategy to work.  _DRAWER_BASE_POSE is set during _reset_actors.
        # self._drawer = self._actor_manager.add_from_usd_file(
        #     name='drawer', asset_path=DRAWER_ASSET_PATH, pose=_DRAWER_BASE_POSE,
        # )
        self._drawer = self._actor_manager.add_from_usd_file(
            name='drawer',
            asset_path=DRAWER_ASSET_PATH,
            pose=_DRAWER_BASE_POSE,
        )
        """self._hide_prim("/World/envs/env_0/drawer")

        self._drawer_visual = self._actor_manager.add_rigid_from_usd_file(
            name='drawer_visual',
            asset_path=DRAWER_VISUAL_ASSET_PATH,
            pose=_DRAWER_BASE_POSE,
        )
        self._drawer_visual.freeze()"""


    def _random_init_poses(self, n: int, min_dist: float = 0.15) -> list:
        """
        Generate n non-overlapping random poses on the table, avoiding the sorter.

        x : uniform in [0.1, 1.0] — rejected if inside sorter footprint
        y : uniform in [-0.35, 0.35] — rejected if inside sorter footprint
        z : TABLE_SPAWN_Z (fixed)
        rz: uniform in [0, 2π]
        """
        MAX_ATTEMPTS = 200
        SORTER_X_MIN = 0.3

        SORTER_X_MAX = 0.7  
        SORTER_Y_MIN = -0.2
        SORTER_Y_MAX =  0.2
        SORTER_MARGIN = 0.05

        # ── Table spawn bounds ────────────────────────────────────────────────────────
        TABLE_X_MIN = 0.1
        TABLE_X_MAX = 0.75
        TABLE_Y_MIN = -0.45
        TABLE_Y_MAX =  0.45

        fx_min = SORTER_X_MIN - SORTER_MARGIN
        fx_max = SORTER_X_MAX + SORTER_MARGIN
        fy_min = SORTER_Y_MIN - SORTER_MARGIN
        fy_max = SORTER_Y_MAX + SORTER_MARGIN

        def _in_sorter(x: float, y: float) -> bool:
            return fx_min < x < fx_max and fy_min < y < fy_max

        poses = []
        while len(poses) < n:
            for _ in range(MAX_ATTEMPTS):
                x  = self.rng.uniform(TABLE_X_MIN, TABLE_X_MAX)
                y  = self.rng.uniform(TABLE_Y_MIN, TABLE_Y_MAX)
                rz = self.rng.uniform(0.0, 2 * np.pi)

                if not _in_sorter(x, y):
                    q = np.array([np.cos(rz / 2), 0.0, 0.0, np.sin(rz / 2)])
                    candidate = Pose([x, y, TABLE_SPAWN_Z], q)

                    too_close = any(
                        np.linalg.norm(candidate.p[:2] - p.p[:2]) < min_dist
                        for p in poses
                    )
                    if not too_close:
                        poses.append(candidate)
                        break
            else:
                raise RuntimeError(
                    f"Could not place object {len(poses)+1}/{n} after "
                    f"{MAX_ATTEMPTS} attempts — reduce n or min_dist."
                )

        return poses
    def _reset_actors(self):
        self._robot_manager._reset_idx()
        # Randomly choose nb of shape present on the tables
        n = self.rng.integers(2, len(ALL_SHAPE_NAMES))
        # Choose which shapes appear this episode
        chosen_indices = self.rng.choice(len(ALL_SHAPE_NAMES), size=n, replace=False)
        self._active_names: list[str] = [ALL_SHAPE_NAMES[i] for i in chosen_indices]

        # Choose target and sample instruction
        target_idx = int(self.rng.integers(0, n))
        self._target_name: str = self._active_names[target_idx]
        instruction_pool = SHAPE_CONFIGS[self._target_name]['instructions']
        self.instruction = str(self.rng.choice(instruction_pool))

        slot_order = self.rng.permutation(n)
        
        final_poses = self._random_init_poses(n, min_dist=0.15)
        final_poses_dict = {}

        for obj_idx, name in enumerate(self._active_names):
            slot = int(slot_order[obj_idx])
            final_poses_dict[name] = final_poses[slot]  
            print(name, final_poses[slot])

        i = 0
        for name in ALL_SHAPE_NAMES:
            self._shapes[name].set_pose(
                 Pose([OFFSCREEN_X, OFFSCREEN_Y_START - i * GRID_SPACING_Y, OFFSCREEN_Z],
                     [1, 0, 0, 0]))
            i += 1

        for name, pose in final_poses_dict.items():
            self._shapes[name].set_pose(Pose([pose.p[0], pose.p[1], SPAWN_SAFE_Z], pose.q))

        for name, pose in final_poses_dict.items():
            self._shapes[name].set_pose(pose)
        self._drawer.set_pose(_DRAWER_BASE_POSE)

        self._success_steps: int = 0
        self.domain_rand_params = {
            'active_shapes': self._active_names,
            'target_shape': self._target_name,
            'instruction': self.instruction,
        }


    def _build_grasp_pose(self) -> tuple:
        target = self._shapes[self._target_name]
        cfg    = SHAPE_CONFIGS[self._target_name]
        obj_p  = target.get_pose().p

        if self._target_name == 'triangle' or self._target_name == 'moon' :
            base_close_axis = np.array([0.0, 1.0, 0.0])
        else :
            base_close_axis = np.array([1.0, 0.0, 0.0])
        q = self._shapes[self._target_name].get_pose().q
        w, x, y, z = float(q[0]), float(q[1]), float(q[2]), float(q[3])
        R = np.array([
            [1-2*(y*y+z*z),   2*(x*y-z*w),   2*(x*z+y*w)],
            [  2*(x*y+z*w), 1-2*(x*x+z*z),   2*(y*z-x*w)],
            [  2*(x*z-y*w),   2*(y*z+x*w), 1-2*(x*x+y*y)],
        ])
        close_axis = R @ base_close_axis
        grasp_p = obj_p \
                + np.array([0.0, 0.0, cfg['grasp_z']]) 
        
        grasp_pose = construct_grasp_pose(
            grasp_p,
            np.array([0.0, 0.0, 1.0]),
            close_axis,
        )
        contact_idx = target.register_point(pose=grasp_pose, type='contact')
        print("GRASP POSE", grasp_pose)
        return grasp_pose, contact_idx

    def pre_move(self):
        print("A")
        self.move(self.atom.open_gripper(force=self.cfg.force_fast,steps=20))
        print("A")

    def _compute_z_rotation_correction(self, shape_name: str) -> float:
        """Returns the minimum Z-rotation (radians) to align shape with its hole."""
        cfg = SHAPE_CONFIGS[shape_name]
        if cfg['canonical_axis'] is None:
            return 0.0  # cylinder: any rotation is valid

        q_obj = self._shapes[shape_name].get_pose().q  # [w, x, y, z]
        print("QUATERNION", q_obj)

        c_local = np.array(cfg['canonical_axis'], dtype=float)
        # 1. define in sorter frame
        t_sorter = np.array(cfg['target_sorter_axis'])

        # 2. get sorter rotation
        q_sorter = self._drawer.get_pose().q
        def quat_to_matrix(q):
            w, x, y, z = q
            return np.array([
                [1-2*(y*y+z*z),   2*(x*y-z*w),   2*(x*z+y*w)],
                [  2*(x*y+z*w), 1-2*(x*x+z*z),   2*(y*z-x*w)],
                [  2*(x*z-y*w),   2*(y*z+x*w), 1-2*(x*x+y*y)],
            ])
        R_sorter = quat_to_matrix(q_sorter)

        # 3. convert to world
        t_world = R_sorter @ t_sorter

        # Rotate canonical axis to world frame
        # Using scipy or manual quaternion rotation:
        w, x, y, z = q_obj
        R = np.array([
            [1-2*(y*y+z*z),   2*(x*y-z*w),   2*(x*z+y*w)],
            [  2*(x*y+z*w), 1-2*(x*x+z*z),   2*(y*z-x*w)],
            [  2*(x*z-y*w),   2*(y*z+x*w), 1-2*(x*x+y*y)],
        ])
        c_world = R @ c_local

        # Project onto XY, compute angle
        cx, cy = c_world[0], c_world[1]
        tx, ty = t_world[0], t_world[1]
        theta0 = np.arctan2(cx * ty - cy * tx, cx * tx + cy * ty)

        # Snap to best symmetric equivalent
        N = cfg['symmetry_order']
        candidates = [theta0 + k * 2 * np.pi / N for k in range(N)]
        # Wrap to [-pi, pi]
        candidates = [(a + np.pi) % (2 * np.pi) - np.pi for a in candidates]
        theta_star = min(candidates, key=abs)

        return theta_star
    
    def _play_once(self):
        """Grasp the target shape and drop it into the drawer."""
        cfg = SHAPE_CONFIGS[self._target_name]
        _, contact_idx = self._build_grasp_pose()
        # 1a. Move explicitly above the object (guaranteed hover, no cuRobo soft cost)
        obj_p = self._shapes[self._target_name].get_pose().p
        ee_now = self.atom.get_arm_pose()
        approach_extra_z = 0.25
        above_obj = Pose(
            [obj_p[0], obj_p[1], obj_p[2] + cfg['grasp_z'] + approach_extra_z],
            ee_now.q,
        )
        self.move(self.atom.move_to_pose(above_obj), time_dilation_factor=0.5)

        # 1b. Descend straight onto the grasp point
        self.move(self.atom.grasp_actor(
            self._shapes[self._target_name],
            contact_point_id=contact_idx,
            is_close=False,
        ))
        force_to_apply = self.cfg.force_slow if self._target_name == 'moon' else self.cfg.force_fast 
        pos_floor = cfg.get('grasp_pos_floor', 0.0)                                                                             
        self.move(self.atom.close_gripper(pos=pos_floor, force=force_to_apply))
        robot = self._robot_manager                                                                                                                                                                                                                                 
        fingers = robot.robot.data.joint_pos[0, robot._gripper_ids]
        print(f"[DEBUG] Finger joints: j1={fingers[0]:.5f}  j2={fingers[1]:.5f}  "                                                                                                                                                                                  
                f"asymmetry={abs(fingers[0]-fingers[1])*1000:.2f} mm")                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    
        inhand = robot.get_inhand_pose(self._shapes[self._target_name])                                                                                                                                                                                             
        print(f"[DEBUG] In-hand offset (gripper-center frame): {inhand.p}")  

        
        # 2. Lift clear of neighbouring shapes and above the sorter top (0.40 m)
        # Grasp is near the piece top (~0.23 m); lift 0.25 m → EE at ~0.48 m
        self.move(self.atom.move_by_displacement(z=0.2))

        self.check_mid_failure()

        # 3. Move above the correct hole for this shape.
        # The sorter is rotated 90° around Z, so its local X axis (hole layout)
        # maps to world Y.  Apply hole_x_offset along world Y.
        drawer_p   = self._drawer.get_pose().p
        hole_y_off = cfg['hole_x_offset']
        ee_now     = self.atom.get_arm_pose()

        above_hole = Pose(
            [drawer_p[0], drawer_p[1] + hole_y_off, ee_now.p[2]],
            ee_now.q,
        )
        self.move(self.atom.move_to_pose(above_hole))
        # Correct for cuRobo FK vs Isaac Lab FK residual XY error.
       

        # 4. Lower into the hole (sorter top at 0.40 m, hole depth 0.34 m)
        # Drop by 0.15 m → EE at ~0.33 m, well inside the 0.34 m deep hole
        self.move(self.atom.move_by_displacement(z=-0.12))
        def correct_angle():
            theta = self._compute_z_rotation_correction(self._target_name)
            print("ROTATING OF THETA", theta)
            if abs(theta) > np.radians(2.0):  # 2° dead-band
                self.move(self.atom.rotate_wrist_z(theta))

        def correct_position():
            obj_p = self._shapes[self._target_name].get_pose().p
            x_err = drawer_p[0]              - obj_p[0]
            y_err = drawer_p[1] + hole_y_off - obj_p[1]
            if abs(x_err) > 0.002 or abs(y_err) > 0.002:
                self.move(self.atom.move_by_displacement(x=x_err, y=y_err), time_dilation_factor=0.5)

        SUCCESS_DESCENT = 0.1   # m — exit both loops if we descend this much
        STEP_DOWN       = 0.005 # m — per step
        STUCK_TOL       = 0.001 # m — if actual movement < this we consider it stuck

        nb_try = 0
        insertion_success = False
        while nb_try < 3 and not insertion_success:
            print("NB TRY", nb_try)
            self.move(self.atom.move_by_displacement(z=0.03), time_dilation_factor=0.5)
            correct_angle()
            correct_position()
            self.move(self.atom.move_by_displacement(z=-0.03), time_dilation_factor=0.5)
            z_start    = self._robot_manager.get_ee_pose().p[2]
            z_previous = z_start
            total_descended = 0.0

            while total_descended < SUCCESS_DESCENT:
                self.move(self.atom.move_by_displacement(z=-STEP_DOWN), time_dilation_factor=0.5)
                z_now      = self._shapes[self._target_name].get_pose().p[2]
                actual_step = z_previous - z_now
                total_descended = z_start - z_now
                if actual_step < STUCK_TOL:
                    print(f"[descent] STUCK at total={total_descended*1000:.1f} mm, retrying")
                    break
                z_previous = z_now
            else:
                insertion_success = True
                print(f"[descent] SUCCESS after {nb_try+1} tries, "
                    f"descended {total_descended*1000:.1f} mm")
                break

            nb_try += 1

        if not insertion_success:
            print(f"[descent] FAILED after {nb_try} tries")
        

        self.move(self.atom.open_gripper(force=self.cfg.force_fast, steps=40))
        # 6. Hold for final observation frames
        self.delay(10, is_save=True)

    def check_mid_failure(self) -> bool:
        pose_object = self._shapes[self._target_name].get_pose().p
        pose_ee     = self._robot_manager.get_gripper_center_pose().p
        return np.linalg.norm(pose_object - pose_ee) > 0.1
        
    def check_success(self) -> bool:
        target      = self._shapes[self._target_name]
        drawer_p    = self._drawer.get_pose().p

        hole_y_off  = SHAPE_CONFIGS[self._target_name]['hole_x_offset']
        hole_p      = np.array([drawer_p[0], drawer_p[1] + hole_y_off, drawer_p[2]])
        obj_p       = target.get_pose().p


        xy_ok  = np.all(np.abs(obj_p[:2] - hole_p[:2]) < _SUCCESS_XY_TOL)
        print("xy_ok",xy_ok)

        print("Z1", obj_p[2])
        print("Z2",drawer_p[2])
        z_ok   = obj_p[2] < drawer_p[2] + _SUCCESS_Z_MIN
        print("z_ok",z_ok)
        in_zone = xy_ok and z_ok

        print(
            f'[puts_smalls_shapes_sorter] target={self._target_name}'
            f'  active={self._active_names}'
            f'  xy_err={np.linalg.norm(obj_p[:2] - hole_p[:2]):.3f} m'
            f'  success_steps={self._success_steps}'
        )
        return in_zone
