# ACT-specific arguments
state_dim: 8
kl_weight: 10.0
chunk_size: 50
hidden_dim: 512
dim_feedforward: 3200

temporal_agg: true
device: cuda:0

# DETR parser args
ckpt_dir: null
policy_class: ACT
num_steps: 4000
num_epochs: null

# Model training params
batch_size: 64
save_freq: 1000
position_embedding: sine
lr_vision_backbone: 0.00001
weight_decay: 0.0001
lr: 0.00001
masks: false
dilation: false
backbone: resnet18
nheads: 8
enc_layers: 4
dec_layers: 7
pre_norm: false
dropout: 0.1
camera_names:
  - cam_high
  - cam_wrist

# tactile args
tactile_names:
  - tac_left
  - tac_right
lr_tactile_backbone: 0.00001
tactile_masks: false
tactile_backbone: resnet18
tactile_ckpt: encoder/ablation/marker_rgb_depth/resnet18/20260116-173421/best.pth
tactile_dilation: false